### PR TITLE
Remove empty while loop

### PR DESCRIPTION
**Pull request by RoverWire**
- This empty loop was causing me some problems on checkout. Now it works fine.

### CODE REVIEW

**Comment by manmartinez** [comment]
@RoverWire We do need that loop as it moves the order through the checkout steps as far as it can

**Comment by RoverWire** [comment]
It causes me problems on checkout, when I dropped, all works fine.

**Comment by manmartinez** [comment]
Can you please describe what problems it causes? Your PR breaks the specs because the loop provides functionality we are expecting

**Comment by jordan-brough** [comment]
@RoverWire trying to think of how this might break things for you.  Is it possible that your state machine allows you to transition to complete via `next`, and this code makes the order go too far?

**Comment by RoverWire** [comment]
In fact yes, it breaks with problem related with state machine and does not allows to continue with checkout, when I remove it, all works fine.

**Comment by jordan-brough** [comment]
@RoverWire can you give more details on what exactly is happening?  You said:

> it breaks with problem related with state machine and does not allows to continue with checkout

How exactly does it break?  Do you have any error messages or stack traces you can paste in here?  Does the end user see any error messages?

**Comment by jordan-brough** [comment]
@RoverWire what are the states of your state machine?  What is your output for `Spree::Order.checkout_steps`?

The default for Solidus is this:

``` ruby
>> pp Spree::Order.checkout_steps
{:address=>{},
 :delivery=>{},
 :payment=>
  {:if=>
    #<Proc:0x007ff890216e80@/Users/jordan/repos/solidus/core/app/models/spree/order.rb:25 (lambda)>},
 :confirm=>{}}
```

**Comment by RoverWire** [comment]
On the project, we are using:

```
  checkout_flow do
    go_to_state :address
    go_to_state :delivery
    go_to_state :payment
    go_to_state :complete
  end
```

And the error displayed when I use the gem as it: 

state-machine-error

removing the loop solves the problem on my case.

**Comment by jordan-brough** [comment]
@RoverWire any chance you'd be able to add a failing spec to this PR?

**Comment by RoverWire** [comment]
@jordan-brough I will close this PR since I realize that the original problem is the project's state machine. Thanks for your help.

**Pull request closed without merging**
