### PR TITLE
added gateway attribute to SpreeAmazon::Order in complete_amazon_orde…

### PR DESCRIPTION
**Pull request by acreilly**
…r! so it wont error out on SpreeAmazon::Order#initialize

### CODE REVIEW

**Comment by jordan-brough** [comment]
@acreilly thanks!  Could we add a spec that covers this?  More tests overall would make it easier for people like us at LostMy.Name (who don't use the Solidus frontend) to help improve this repo.

**Comment by manmartinez** [comment]
@acreilly yeah if we can add some specs that catch this error it'd be awesome we can probably use the existing controller specs and just tweak them so they notice this error

**Comment by jordan-brough** [comment]
@manmartinez @acreilly I remembered that I actually have a spec that covers this (and the same fix) in some code we're using but haven't PR'd yet.  If we can get this in:
https://github.com/boomerdigital/solidus_amazon_payments/pull/24
I will be able to get that other code out as a PR.

**Comment by acreilly** [comment]
@jordan-brough Doesn't look like this change was in that PR, am I missing something?

**Comment by acreilly** [comment]
@jordan-brough sorry just saw you said you have it in another PR. @manmartinez merged #24, Can you get that PR up since without that fix, this gem isn't working for anyone trying to use it.

**Comment by jordan-brough** [comment]
@acreilly yup will do later today!  It's very helpful to have that other PR merged. Thanks @manmartinez.

**Comment by jordan-brough** [comment]
@acreilly I've opened #33 which includes this in one of the commits.

**Comment by manmartinez** [comment]
This was addressed in #33

**Pull request closed without merging**
