### PR TITLE
Support Multiple Accounts for Multiple Currencies

### PR DESCRIPTION
**Pull request by jordan-brough**
NOTE: Going through this PR commit by commit should be easier
to read than looking at the entire diff all at once.

Amazon requires a separate account for each currency for Amazon
Payments. This PR supports having multiple Amazon accounts for
each currency by moving the Amazon Payment credentials from
`SpreeAmazon::Config` to `Spree::Gateway::Amazon` and adds
`preferred_currency` to `Spree::Amazon::Gateway` so that you
can have one Gateway for each currency.

We've tried to write this in a backward-compatible way, with
deprecation warnings.

@chrisradford and I worked on this together.

### CODE REVIEW

**Comment by jordan-brough** [comment]
@manmartinez I believe this is ready to go, let me know if you think.

**Comment by jordan-brough** [comment]
@manmartinez I should probably bump the gem version to 4.0 given the breaking changes?

**Comment by manmartinez** [comment]
@jordan-brough the gem version is a good point, I think we ported over the version from spree_pay_with_amazon, we should probably start with our own version since we pretty much rewrote the extension, do you think we should start with 1.0.0?

**Comment by jordan-brough** [comment]
@manmartinez that sounds good to me. I've pushed an update with that. Good to merge?

**Comment by manmartinez** [comment]
This looks great! Thanks for all the hard work!

**Pull request merged**
