### PR TITLE
Remove unused AppConfiguration decorator

### PR DESCRIPTION
**Pull request by jordan-brough**
I think this was missed in #12.

### CODE REVIEW

**Comment by jordan-brough** [comment]
I believe the specs are failing because of the issue that #14 fixes.

**Comment by manmartinez** [comment]
@jordan-brough I just merged #14 can you please rebase this to see if it fixes the failing specs?

**Comment by jordan-brough** [comment]
@manmartinez thanks!  I've rebased and the specs are green now.

**Comment by manmartinez** [comment]
Awesome! Thanks for the PR!

**Pull request merged**
